import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./GlobalReducer/Provider";

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ['400','600']
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
      <body className={poppins.className}>{children}</body>
      </html>
    </Providers>
  );
}